import 'package:flutter/material.dart';

const String imagesPath = "assets/images";
final List<ImageProvider> cardImage = <ImageProvider>[
  AssetImage('$imagesPath/abaniko.png'),
  AssetImage('$imagesPath/agila.png'),
  AssetImage('$imagesPath/abaniko.png'),
  AssetImage('$imagesPath/anahaw.png'),
  AssetImage('$imagesPath/anting_anting.png'),
  AssetImage('$imagesPath/bahay_kubo.png'),
  AssetImage('$imagesPath/balut.png'),
  AssetImage('$imagesPath/bangka.png'),
  AssetImage('$imagesPath/bayong.png'),
  AssetImage('$imagesPath/barong_tagalog.png'),
  AssetImage('$imagesPath/buko_juice.png'),
  AssetImage('$imagesPath/bulkang_mayon.png'),
  AssetImage('$imagesPath/chocolate_hills.png'),
  AssetImage('$imagesPath/halo-halo.png'),
  AssetImage('$imagesPath/jeep.png'),
  AssetImage('$imagesPath/kalabaw.png'),
  AssetImage('$imagesPath/kalesa.png'),
  AssetImage('$imagesPath/kariton.png'),
  AssetImage('$imagesPath/linga.png'),
  AssetImage('$imagesPath/mangga.png'),
  AssetImage('$imagesPath/mapa.png'),
  AssetImage('$imagesPath/narra.png'),
  AssetImage('$imagesPath/parol.png'),
  AssetImage('$imagesPath/pawikan.png'),
  AssetImage('$imagesPath/perlas.png'),
  AssetImage('$imagesPath/puto.png'),
  AssetImage('$imagesPath/rizal_monument.png'),
  AssetImage('$imagesPath/sabong.png'),
  AssetImage('$imagesPath/salakot.png'),
  AssetImage('$imagesPath/sampaguita.png'),
  AssetImage('$imagesPath/saya.png'),
  AssetImage('$imagesPath/taho.png'),
  AssetImage('$imagesPath/tricycle.png'),
  AssetImage('$imagesPath/tsinelas.png'),
  AssetImage('$imagesPath/watawat.png'),
];
